export interface Store {
  id: number;
  name: string;
  shortName?: string;
  address?: string;
  lat?: string;
  lon?: string;
  province?: string;
  district?: string;
  ward?: string;
  isAvailable?: boolean;
  active?: boolean;
  email?: string;
  phone?: string;
  fax?: string;
  createDate?: string;
  type?: number;
  roomRentMode?: string | null;
  reportDate?: string | null;
  groupId?: number | null;
  openTime?: string | null;
  closeTime?: string | null;
  defaultAdminPassword?: string | null;
  hasProducts?: boolean;
  hasNews?: boolean;
  hasImageCollections?: boolean;
  hasMultipleLanguage?: boolean;
  hasWebPages?: boolean;
  hasCustomerFeedbacks?: boolean;
  brandId?: number;
  hasOrder?: boolean;
  hasBlogEditCollections?: boolean;
  logoUrl?: string;
  fbAccessToken?: string | null;
  storeFeatureFilter?: string;
  runReport?: boolean;
  attendanceStoreFilter?: string | null;
  storeCode?: string;
  posId?: number | null;
  storeConfig?: string | null;
  defaultDashBoard?: string | null;
  paymentTypeApply?: string | null;
  modeStore?: string | null;
}